src/Web/Catalog.WebForms/Catalog.WebForms/Catalog.WebForms.csproj
src/Web/Catalog.WebForms/Catalog.WebForms/Default.aspx.cs
src/Web/Catalog.WebForms/Catalog.WebForms/Global.asax.cs
src/Web/Catalog.WebForms/Catalog.WebForms/Modules/AutoFacHttpModule.cs
src/Web/Catalog.WebForms/Catalog.WebForms/Web.config

Instead of creating a global service locator object, create an HTTP module that injects dependencies using AutoFac when the page is created.
Based on the solution written here: https://blogs.msdn.microsoft.com/webdev/2016/10/19/modern-asp-net-web-forms-development-dependency-injection/

Use DI instead of a service locator

---

src/Console/eShopConsole/Properties/launchSettings.json
src/Services/Basket/Basket.API/Properties/launchSettings.json
src/Services/Catalog/Catalog.API/Properties/launchSettings.json
src/Services/Ordering/Ordering.API/Properties/launchSettings.json
src/Web/WebMVC/Properties/launchSettings.json

The Docker profiles are out-of-date and no longer used by Docker tools. The change is to remove them to avoid issues with VS 2017 RTW.

Removes Docker profile from launchSettings.json

---

src/Web/Catalog.WebForms/Catalog.WebForms/Catalog.WebForms.csproj
src/Web/Catalog.WebForms/Catalog.WebForms/Default.aspx.cs
src/Web/Catalog.WebForms/Catalog.WebForms/Modules/AutoFacHttpModule.cs
src/Web/Catalog.WebForms/Catalog.WebForms/Web.config
src/Web/Catalog.WebForms/Catalog.WebForms/packages.config

This is necessary for C# 7 feature support.
See the pattern match is statement in AutoFacHttpModule.
@CESARDELATORRE this same change (update Microsoft.Net.Compilers package to 2.0 would likely be necessary for the MVC, SPA, and WebAPI packages to support the new language features.  I can do that on the dev branch if you'd like.

Update Compiler package

---

src/Services/Ordering/Ordering.API/Application/Commands/CreateOrderCommandHandler.cs
src/Services/Ordering/Ordering.API/Infrastructure/AutofacModules/ApplicationModule.cs
src/Services/Ordering/Ordering.Domain/AggregatesModel/BuyerAggregate/IBuyerRepository.cs
src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/IOrderRepository.cs
src/Services/Ordering/Ordering.Infrastructure/Repositories/BuyerRepository.cs
src/Services/Ordering/Ordering.Infrastructure/Repositories/OrderRepository.cs
test/Services/UnitTest/Ordering/Application/NewOrderCommandHandlerTest.cs

`IOrderRepository` makes more sense than `IOrderRepository<Order>` since we don't need `IOrderRepository<Buyer>`.

use non generic repository interface

---

src/Services/Basket/Basket.API/Controllers/BasketController.cs
src/Services/Basket/Basket.API/Model/IBasketRepository.cs
src/Services/Basket/Basket.API/Model/RedisBasketRepository.cs
src/Services/Ordering/Ordering.Infrastructure/Repositories/BuyerRepository.cs
src/Services/Ordering/Ordering.Infrastructure/Repositories/OrderRepository.cs
test/Services/IntegrationTests/Services/Basket/RedisBasketRepositoryTests.cs
test/Services/UnitTest/Basket/Application/BasketWebApiTest.cs

Fix for #61 As requested in the issue simple change of names to fit the naming convention for TAP. 
Ordering repositories will be changed to async when we migrate to ef core 1.1.1

Fix #61 Async suffix for namig convention.

---

src/Web/WebSPA/package.json

#72  Resolved SPA incompatibilities with dependencies when installing a newer node version.
The actual version of node-sass dependency was not compatible with newest node versions so that the node-sass lib version used has been updated

Resolved SPA incompatibilities with dependencies 

---

src/Web/WebMVC/Controllers/AccountController.cs
src/Web/WebMVC/Controllers/CatalogController.cs
src/Web/WebMVC/Extensions/HttpClientExtensions.cs
src/Web/WebMVC/Extensions/SessionExtensions.cs
src/Web/WebMVC/Services/BasketService.cs
src/Web/WebMVC/Services/CatalogService.cs
src/Web/WebMVC/Services/IdentityParser.cs
src/Web/WebMVC/Services/Utilities/HttpApiClient.cs
src/Web/WebMVC/Services/Utilities/HttpApiClientWrapper.cs
src/Web/WebMVC/ViewComponents/Cart.cs
src/Web/WebMVC/ViewComponents/CartList.cs
src/Web/WebMVC/ViewModels/Annotations/CardExpiration.cs
src/Web/WebMVC/ViewModels/Basket.cs
src/Web/WebMVC/ViewModels/CartViewModels/IndexViewModel.cs
src/Web/WebMVC/ViewModels/Order.cs

@CESARDELATORRE Let me know if this should be targetting master instead of dev. I've seen  ongoing work in each branch.
*Controllers/AccountController:*
Replace single line methods with expression bodied members.
Includes constructor, C# 7 feature.
*Controllers/CatalogController:*
Remove unnecessary ToString() call.
Replace single line methods with expression bodied members.
*Extensions/HttpClientExtensions:*
Replace single line methods with expression bodied members.
*Extensions/SessionExtensions:*
Replace single line methods with expression bodied members.
*Services/BasketService:*
Remove unnecessary ToString() calls.
Add ?? to simplify conditional initialization
Use TryGetValue and out variable initialization to simplify Quantity
calculation
*Services/CatalogService:*
Use Value<T> …

C# 7 language feature updates

---

docker-compose.override.yml
docker-compose.prod.yml
src/Services/Identity/Identity.API/Configuration/Config.cs
src/Services/Identity/Identity.API/Startup.cs
src/Services/Identity/Identity.API/appsettings.json

This PR solves the issues detected in Xamarin UWP application on signin.
Basically, if the origin of the OIDC "Callback URL" do not exist, UWP's WebView do not raise any event, and the Xamarin app can't know that the signin process has finished. This do not happen on Android nor iOS. Only UWP.
So, Xamarin app configuration was updated to use a existing origin (same as IdSvr) and IdSvr config was updated to allow this new callbackurl.
The new callbackurl is xxxx/xamarincallback, where xxxx is the IdSvr origin (host+port).
Note that localhost is not valid, because Webview complains about it also, so if you are running services in your machine, you must use your IP.
Docker-compose files have been udpated to enforce this.

Idsvr new config

---

src/Services/Basket/Basket.API/Model/RedisBasketRepository.cs
src/Services/Identity/Identity.API/Startup.cs
src/Web/WebMVC/Startup.cs
src/Web/WebSPA/Startup.cs

A couple small changes to resolve issues I found hosting the app in Kubernetes:
1. Setting application discriminators prevents an app trying to decrypt another's cookie
1. When `Basket.API` connects to Redis, don't call `Dns.GetHostAddressesAsync` if the connection string is an IP address. It may return `[::1, 127.0.0.1]` for `"127.0.0.1"`. Then `ips.First()` is `::1`, which the Redis client can't handle.

Set application discriminators, work around Redis client issue

---

src/Services/Ordering/Ordering.API/Application/Queries/IOrderQueries.cs
src/Services/Ordering/Ordering.API/Application/Queries/OrderQueries.cs
test/Services/UnitTest/Ordering/Application/OrdersWebApiTest.cs

The methods that return collections should return
Task<IEnumerable<dynamic>> not Task<dynamic>

Fix API signatures for collections

---

src/Services/Ordering/Ordering.API/Application/Queries/IOrderQueries.cs
src/Services/Ordering/Ordering.API/Application/Queries/OrderQueries.cs
src/Services/Ordering/Ordering.API/Controllers/OrdersController.cs
test/Services/UnitTest/Ordering/Application/OrdersWebApiTest.cs

This fixes the problem introduced in the prior PR by adding back the async state machines to the ordering queries.  See second commit for details.
/cc @CESARDELATORRE

Use IEnumerable<dynamic> instead of dynamic for collections

---

cli-mac/build-bits.sh
docker-compose.ci.build.yml

Reverts dotnet-architecture/eShopOnContainers#191

Revert "Revert "Fix mac ci build""

---

src/BuildingBlocks/Resilience/Resilience.Http/StandardHttpClient.cs

DoPostPutAsync in StandardHttpClient was locked to POST methods. Fixed to allow PUTs.

Fix StandardHttpClient's DoPostPutAsync Method

---

src/BuildingBlocks/Resilience/Resilience.Http/StandardHttpClient.cs

In a couple of places the AuthenticationToken is being used instead of the AuthenticationMethod parameter.  This results in failed requests.

StandardHttpClient setting Authentication Header

---

src/Services/Location/Locations.API/Dockerfile.nanowin
src/Services/Marketing/Marketing.API/Dockerfile.nanowin
src/Services/Payment/Payment.API/Dockerfile.nanowin
src/Web/WebStatus/Dockerfile.nanowin

CLI-Windows using wrong dll names in Dockerfile.nanowin
Looks like nobody have tested windows version for a long time

CLI-Windows using wrong dll names in Dockerfile.nanowin

---

cli-mac/build-bits.sh
cli-windows/build-bits.ps1

release publish configuration for win/mac, because for Linux it's already done

release publish configuration for win/mac, because for Linux it's already done

---

cli-windows/build-bits.ps1

it's working 2m 24s instead of 3m 48s (sequential execution)
theis only one problem... write-host not working inside the workflow
P.S. in both cases comparison was without "dotnet restore command", because it's not mandatory in .net core sdk 2.0

Parallel dotnet build process.

---

cli-mac/build-bits.sh
cli-windows/build-bits-simple.ps1
cli-windows/build-bits.ps1
k8s/deploy.ps1

"Starting with .NET Core 2.0 SDK, dotnet restore runs implicitily when you run dotnet build." (C) https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x

dotnet restore not needed in cli 2.0

---

src/Services/Basket/Basket.API/Controllers/BasketController.cs
src/Services/Catalog/Catalog.API/Controllers/CatalogController.cs
src/Services/Catalog/Catalog.API/Controllers/PicController.cs
src/Services/Location/Locations.API/Controllers/LocationsController.cs
src/Services/Marketing/Marketing.API/Controllers/CampaignsController.cs
src/Services/Marketing/Marketing.API/Controllers/LocationsController.cs
src/Services/Marketing/Marketing.API/Properties/launchSettings.json
src/Services/Ordering/Ordering.API/Controllers/OrdersController.cs

https://github.com/dotnet-architecture/eShopOnContainers/issues/305
@CESARDELATORRE

swagger response types and code 

---

src/Services/Basket/Basket.API/IntegrationEvents/EventHandling/ProductPriceChangedIntegrationEventHandler.cs
src/Services/Basket/Basket.API/Model/IBasketRepository.cs
src/Services/Basket/Basket.API/Model/RedisBasketRepository.cs
test/Services/IntegrationTests/Services/Basket/RedisBasketRepositoryTests.cs

https://github.com/dotnet-architecture/eShopOnContainers/issues/62
I made some clean-up for the RedisBasketRepository.
1) Removing `GetDatabase` from the methods
2) Inject `ConnectionMultiplexer` through constructor injection.
There are some lines in `Startup.cs`
```csharp
services.AddSingleton<ConnectionMultiplexer>(sp =>
{
var settings = sp.GetRequiredService<IOptions<BasketSettings>>().Value;
ConfigurationOptions configuration = ConfigurationOptions.Parse(settings.ConnectionString, true);           
configuration.ResolveDns = true;
return ConnectionMultiplexer.Connect(configuration);
});
```
Why don't use them? :)
3) `GetUsersAsync` -> `GetUsers`. 'cause there is no need for async after implementing constructor injection
4) Refactoring calls of `GetUsersAsync` method

Fix "DRY up RedisBasketRepository"

---

cli-mac/build-bits.sh

I confirmed that this allows the project to build on Mac, excluding WebSPA which I didn't test. [See comment](https://github.com/dotnet-architecture/eShopOnContainers/issues/107#issuecomment-339161921) for details.
Also note that I had to install bower for this to work which isn't listed in the pre-requisites.
Finally, the [documentation](https://github.com/dotnet-architecture/eShopOnContainers/wiki/04.-Setting-eShopOnContainer-solution-up-in-a-Mac,-VS-Code-and-CLI-environment--(dotnet-CLI,-Docker-CLI-and-VS-Code)#running-the-application) can be updated as well. The list outlining where all the services can be reached is out of date, and in the case of WebSPA, incorrect.

Update project list in mac build script

---

test/Services/IntegrationTests/Services/Basket/RedisBasketRepositoryTests.cs
test/Services/IntegrationTests/Services/Catalog/CatalogScenarios.cs
test/Services/UnitTest/Ordering/Application/OrdersWebApiTest.cs
test/Services/UnitTest/Ordering/Domain/OrderAggregateTest.cs

I tried to build the latest code with [these instructions](https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)) and saw the following issues in the build log:
```
Ordering/Application/OrdersWebApiTest.cs(98,26): error CS1503: Argument 1: cannot convert from 'System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<object>>' to 'System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.eShopOnContainers.Services.Ordering.API.Application.Queries.OrderSummary>>'
Ordering/Application/OrdersWebApiTest.cs(115,26): error CS1503: Argument 1: cannot convert from 'System.Threading.Tasks.Task<object>' to …
```

Fix build errors & warnings

---

NuGet.config

All solutions now restore to the packages directory at the root of
the repository. This fixes packages being restored into the
src/Mobile/packages directory when the eShopOnContainers.Xamarin.sln
is opened.
https://developercommunity.visualstudio.com/content/problem/80508/references-are-broken-even-though-nugets-have-been.html

Configure packages directory for restored NuGet packages

---

src/Services/Payment/Payment.API/Payment.API.csproj
src/Services/Payment/Payment.API/Startup.cs

We are not using Swagger in this api => we don't need this package in a project.
@CESARDELATORRE @ramonTC

drop swagger from payment API

---

src/Services/Identity/Identity.API/Data/ConfigurationDbContextSeed.cs

The `DbSet<T>.Any()` is a database I/O operation, it's should be async.
But the `DbSet<T>.AddAsync<T>(T entity)` is only used to allow special value generators, in the document:
> This method is async only to allow special value generators, such as the one used by  'Microsoft.EntityFrameworkCore.Metadata.SqlServerValueGenerationStrategy.SequenceHiLo', to access the database asynchronously. For all other cases the non async method should be used.
So I think it should be non async.

Fix about some async calls.

---

src/Mobile/eShopOnContainers/eShopOnContainers.TestRunner.iOS/eShopOnContainers.TestRunner.iOS.csproj
src/Mobile/eShopOnContainers/eShopOnContainers.TestRunner.iOS/packages.config

Ever since `src/Mobile/eShopOnContainers/eShopOnContainers.Core/eShopOnContainers.csproj` was moved to .NETStandard (and SDK style .csproj), the eShopOnContainers.TestRunner.iOS.csproj hasn't been compiling in `Debug|iPhone` and `Release|iPhone` configurations. 
Turns out, with the .NETStandard core library, these target/head projects need these references as well to produce a successful build.

Add reference packages to TestRunner app so it builds successfully

---

src/Services/Basket/Basket.API/Basket.API.csproj
src/Services/Catalog/Catalog.API/Catalog.API.csproj
src/Services/Identity/Identity.API/Identity.API.csproj
src/Services/Location/Locations.API/Locations.API.csproj
src/Services/Marketing/Marketing.API/Marketing.API.csproj
src/Services/Ordering/Ordering.API/Ordering.API.csproj
src/Services/Payment/Payment.API/Payment.API.csproj
src/Web/WebMVC/WebMVC.csproj
src/Web/WebSPA/WebSPA.csproj
src/Web/WebStatus/WebStatus.csproj

Kubernetes deployment will fail because of this issue: https://github.com/Microsoft/ApplicationInsights-Kubernetes/issues/73, which is fixed in version 1.0-beta3

Update AI k8s package version, otherwise kubernetes deployment will fail

---

src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs

The "Body" property now uses the already converted "body" variable.
Before, the "body" variable was not used at all.

Removed duplicate string to byte conversion

---

src/Services/Identity/Identity.API/Data/ApplicationDbContextSeed.cs
src/Services/Identity/Identity.API/Data/ConfigurationDbContextSeed.cs
src/Services/Ordering/Ordering.API/Infrastructure/OrderingContextSeed.cs

that don't use the SequenceHiLo key generation strategy, as per https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.addrangeasync?view=efcore-2.0
As a result from an internal post-mortem review of PR #491 with @unaizorrilla, AddRangeAsync should only be used when entities use the SequenceHiLo key generation strategy, and that doesn't happen for the entities updated with this PR

Fix improper use of AddRangeAsync for seeding entities

---

src/Services/Ordering/Ordering.Domain/Events/OrderStartedDomainEvent.cs

Remove private setters to make a class truly immutable. Otherwise, properties can be updated outside of constructor. This also makes code cleaner. Same in docs https://github.com/dotnet/docs/pull/4755

Remove private setters to make class immutable

---

src/Services/Ordering/Ordering.Domain/SeedWork/Entity.cs
src/Services/Ordering/Ordering.Infrastructure/MediatorExtension.cs

This PR is a replacement for #556 
The Entity class should not expose the list of domain events as List<INotification>. This allows to modify the list of events without accessing Add/Remove methods. I propose to return IReadOnlyCollection<INotification> instead and add ClearDomainEvents() method to clear events.

Improved encapsulation of DomainEvents collection in Entity class

---

src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/SettingsViewModel.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/SettingsView.xaml

1. Removed the three unnecessary parent layouts in `SettingsView`.
2. Refactored the `InitializeAsync` method out of the `SettingsViewModel` class, as it was causing a delay rendering the `SettingsView` `Label` instances on iOS.

Performant SettingViews on iOS

---

src/Mobile/eShopOnContainers/eShopOnContainers.Core/GlobalSettings.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Helpers/UriHelper.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/Basket/BasketService.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/Catalog/CatalogService.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/FixUri/FixUriService.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/Identity/IdentityService.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/Location/LocationService.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/Marketing/CampaignService.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/Order/OrderService.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/Settings/ISettingsService.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/Settings/SettingsService.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/User/UserService.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/Base/ViewModelBase.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/LoginViewModel.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/SettingsViewModel.cs
src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/SettingsView.xaml
src/Mobile/eShopOnContainers/eShopOnContainers.UnitTests/Mocks/MockSettingsService.cs

This pull request introduce a separation in the urlbase setting entry to let the user set the url scheme needed in case of Docker or Kubernetes.
The setting menu now shows like this:

Urls for Identity, Gateway Shopping and Marketing added to setting view

---

src/BuildingBlocks/EventBus/EventBus.Tests/TestIntegrationEventHandler.cs
src/BuildingBlocks/EventBus/EventBus.Tests/TestIntegrationOtherEventHandler.cs

Fix an inconsistency between filename and classname of EventBus.Test models.
The file `TestIntegrationOtherEventHandler.cs`  defines the class `TestIntegrationEventHandler `, and the file `TestIntegrationEventHandler .cs`  defines the class `TestIntegrationOtherEventHandler`.

Fix classname of EventBus.Test models

---

src/Services/Ordering/Ordering.API/Infrastructure/OrderingContextSeed.cs
src/Services/Ordering/Ordering.Domain/AggregatesModel/BuyerAggregate/CardType.cs
src/Services/Ordering/Ordering.Domain/SeedWork/Enumeration.cs

Modified Enumeration class to support private constructor for Enum types + refactored orderingContextSeed to use GetAll() method to get predefined types.
This is the code change for #652 issue/refactor and also relates to the https://github.com/dotnet/docs/pull/6209.

Modified Enumeration class to support private constructor

---

src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/Address.cs

Add private setters so deserializing on integration event handler works as expected.
Fixes #725 
Referenced from docs.

Fix for #725 - Address value object not saved

---

src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs
src/Services/Basket/Basket.API/Startup.cs
src/Services/Catalog/Catalog.API/Startup.cs
src/Services/Location/Locations.API/Startup.cs
src/Services/Marketing/Marketing.API/Startup.cs
src/Services/Ordering/Ordering.API/Startup.cs
src/Services/Ordering/Ordering.BackgroundTasks/Startup.cs
src/Services/Ordering/Ordering.SignalrHub/Startup.cs
src/Services/Payment/Payment.API/Startup.cs
src/Services/Webhooks/Webhooks.API/Startup.cs

Use `AsyncEventingBasicConsumer` instead of `EventingBasicConsumer` to properly use async event handlers on consumers.
Taken from http://gigi.nullneuron.net/gigilabs/asynchronous-rabbitmq-consumers-in-net/
Closes #888.
As detected by @falamarzijahromi, the previous implementation was using async event handlers with `EventingBasicConsumer` (which isn't async) and this causes possible out-of-order message handling and improper exception handling. This is also explained in the above article.
Even though the ordering issue doesn't seem to affect eShopOnContainers it was fixed because it's not adecuate to synchronously call async event handlers.
However, the exception handling does affect the services, as will be shown next.
To create this situation you can now force an exception in the …

Use AsyncEventingBasicConsumer in RabbitMQ

---

src/Services/Basket/Basket.API/Controllers/BasketController.cs
src/Services/Basket/Basket.UnitTests/Application/BasketWebApiTest.cs
src/Services/Basket/Basket.UnitTests/Basket.UnitTests.csproj
src/Services/Catalog/Catalog.UnitTests/Catalog.UnitTests.csproj
src/Services/Marketing/Marketing.FunctionalTests/Marketing.FunctionalTests.csproj
src/Services/Marketing/Marketing.FunctionalTests/Properties/launchSettings.json
src/Services/Ordering/Ordering.FunctionalTests/Ordering.FunctionalTests.csproj

Update unit tests projects as per https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#test-app-prerequisites
Fix failling unit tests.
Closes https://github.com/dotnet-architecture/eShopOnContainers/pull/991 as it became outdated

Fix tests projects compilation errors and unit tests failures

---

src/Services/Marketing/Marketing.FunctionalTests/CampaignScenarios.cs

This test is looking for ID = 81, but the test fails when the DB is first built, because the original seed only populates 2 campaign rows. By changing this to ID = 2, the test will pass without having the other POST/PUT tests run several times first.

Get_get_campaign_by_id now fails initially

---

k8s/helm/deploy-all.ps1

All,
I would like to make a small suggestion to not blindly destroy all the containers within the default namespace.
This is too intrusive if the Kubernetes Cluster is not only serving for eShop purposes.
Therefore I would like to suggest that the cleanup tasks gets modified as followed:
Current
````powershell
if ($clean) {
Write-Host "Cleaning previous helm releases..." -ForegroundColor Green
helm delete --purge $(helm ls -q) 
Write-Host "Previous releases deleted" -ForegroundColor Green
}
````
Proposal:
````powershell
if ($clean) {
Write-Host "Cleaning previous helm releases..." -ForegroundColor Green
helm delete --purge $(helm ls -q eshop)
Write-Host "Previous releases deleted" -ForegroundColor Green
}
````
This will filter out only those helm deployments containing the word "eshop". …

limit helm delete to eshop

---

cli-windows/set-dockernat-networkategory-to-private.ps1

Adding powershell script to set DockerNAT network category to private which solves the problem referred in https://github.com/dotnet-architecture/eShopOnContainers/issues/295 and proposal from https://github.com/dotnet/docs/issues/11528. 
This can be a workaround to run this script until docker figures out a better way to solve the issue. 
The setting is required to be done at restart, however, setting this as scheduled task to run this script might help. (I can update the documentation too once this is accepted and merged)

Add Powershell script to set network category to private for DockerNAT.

---

src/Services/Marketing/Marketing.FunctionalTests/UserLocationRoleScenarios.cs

There are 2 tests that use campaignId = 81 that fail when a campaign with that Id does not exist. This is exactly the same scenario as seen in PR #1004.

Fix marketing functional tests that rely on existing campaign

---

src/Web/WebMVC/Views/Campaigns/Details.cshtml
src/Web/WebMVC/Views/Campaigns/Index.cshtml
src/Web/WebMVC/Views/Catalog/Index.cshtml

In some razor views, the model declaration is embedded inside a code block, which makes it difficult for Visual Studio to resolve the model references. This PR moves the model declaration for the affected views outside of the code blocks.

model declarations in razor views resulting in unsolved references

---

run-docker-compose-build.ps1
scripts/restore-packages

Remove unneeded `#!/bin/bash` from script and line endings, to avoid errors from CRLF line endings that come from git config on Windows

Fix restore packages script 

---

src/Web/WebStatus/Views/Shared/Error.cshtml
src/Web/WebStatus/WebStatus.csproj

The Error action in the Home controller in the WebStatus project returns a View that does not exist. This PR adds a simple Error view based on the default error view from the .NET Core MVC template.

add missing Error view for WebStatus project

---

src/Web/WebStatus/appsettings.json

Added health checks urls in appsettings.json, just as they are in appsettings.Development.json.
It looks like when running from VS appsettings.json take precedence over the environment variables in docker-compose.override.yml.
Fixes https://github.com/dotnet-architecture/eShopOnContainers/issues/1024

Fix empty health checks view when running from VS

---

src/Services/Ordering/Ordering.API/Application/Commands/CancelOrderCommandHandler.cs
src/Services/Ordering/Ordering.API/Application/Commands/CreateOrderCommandHandler.cs
src/Services/Ordering/Ordering.API/Application/Commands/IdentifiedCommandHandler.cs
src/Services/Ordering/Ordering.API/Application/Commands/SetAwaitingValidationOrderStatusCommandHandler.cs
src/Services/Ordering/Ordering.API/Application/Commands/SetPaidOrderStatusCommandHandler.cs
src/Services/Ordering/Ordering.API/Application/Commands/SetStockConfirmedOrderStatusCommandHandler.cs
src/Services/Ordering/Ordering.API/Application/Commands/SetStockRejectedOrderStatusCommandHandler.cs
src/Services/Ordering/Ordering.API/Application/Commands/ShipOrderCommandHandler.cs
src/Services/Ordering/Ordering.API/Application/DomainEventHandlers/OrderStartedEvent/ValidateOrAddBuyerAggregateWhenOrderStartedDomainEventHandler.cs
src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs

MediatR supports cancellation tokens in it's IRequestHandler interface, but currently none of the command handlers do anything with them if one is passed.

provide support for cancellation tokens in command handlers

---

src/ApiGateways/Mobile.Bff.Shopping/aggregator/Controllers/BasketController.cs
src/ApiGateways/Web.Bff.Shopping/aggregator/Controllers/BasketController.cs

In the case where there is an existing basket for the current buyer, the UpdateAllBasketAsync action in the BasketController will ignore it. Instead it will always instantiate and return a new basket. This fix uses the current basket if one already exists.

UpdateAllBasketAsync should use the current basket if it exists

---

src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs

Add Task.Yield() to avoid synchronous deadlock by ensuring asynchronous execution.

Fix RabbitMQ deadlock with AsyncEventingBasicConsumer consumer

---

src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs

Currently, the code `nameof(TH)` is printing the value TH in the message. This PR will change it to print the type name in the message e.g. `MyEventHandler`.

Display the type name in the log message

---

k8s/helm/deploy-all.sh

Several fixes in this PR:
* `--docker-password` argument was not correctly handled.
* `--docker-username` was not correctly documented in `usage()`, `--docker-user` was incorrectly referenced instead.
* `--dns aks` argument was not documented at usage.
* No authentication to custom registry was performed in the script, so `--docker-username` and `--docker-password` arguments didn't have any effect. Now it is possible to push the images to custom registry.
* `image_tag` was not aligned with `docker-compose build` output, as it will add `linux-` prefix according to the platform. A check to detect this and tag the images accordingly has been implemented.

Several improvement and fixes in deploy-all.sh

---

src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs

Just a typo in a private const name. Changes `INTEGRATION_EVENT_SUFIX` to `INTEGRATION_EVENT_SUFFIX`.

fix: typo in EventBusServiceBus.cs for "suffix"

---

src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/LoginView.xaml

Added extra brackets } to get XAML compliant again when using converters
Fixes #781

Be sure to have all brackets inside the XAML

---

src/.env
src/Services/Identity/Identity.API/appsettings.json
src/docker-compose-tests.override.yml
src/docker-compose.override.yml
src/docker-compose.prod.yml

Change references from `localhost` to `docker.for.win.localhost` to solve MVC login when using Docker Desktop 2.2.0.0
See the [.env file](https://github.com/dotnet-architecture/eShopOnContainers/blob/fix/docker-2.2-mvc-login/src/.env) for other platforms.
For testing!

Use internal docker dns names

---

src/Web/WebSPA/package-lock.json

Updated serialize-javascript version from 2.1.1 to 3.1.0 as suggested :  https://github.com/dotnet-architecture/eShopOnContainers/network/alert/src/Web/WebSPA/package-lock.json/serialize-javascript/open

Updated serialize-javascript version to 3.1.0

---

src/.env

#1397: Replaced docker.for.win.localhost by host.docker.internal

---

src/Services/Catalog/Catalog.API/Controllers/PicController.cs

Changing File.ReadAllBytes to await File.ReadAllBytesAsync in order to liberate the thread when reading the file.

Change ReadAllBytes to ReadAllBytesAsync in PicController

---

src/Web/WebSPA/appsettings.json

Hi,
in the WebSPA project's appsettings.json the port of PurchaseUrl seems to be wrong but it doesn't cause errors because the matching environment variable in docker-compose.override.yml overrides it.
Commenting out the environment variable results in the catalog not being shown and console errors like:
Access to XMLHttpRequest at 'http://localhost:5200/c/api/v1/catalog/items?pageIndex=0&pageSize=10' from origin 'http://host.docker.internal:5104' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
The change in this PR fixes it.

Fix PurchaseUrl port in WebSPA appsettings.json

---

src/Web/WebMVC/Startup.cs

Fix samesite issue when running eShop from docker-compose locally as by default http protocol is being used
Refer to https://github.com/dotnet-architecture/eShopOnContainers/issues/1391

Fix login issue Exception: Correlation failed

---

src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj
src/BuildingBlocks/WebHostCustomization/WebHost.Customization/WebHost.Customization.csproj
src/NuGet.config
src/Services/Catalog/Catalog.API/Catalog.API.csproj
src/Services/Identity/Identity.API/Identity.API.csproj
src/Services/Identity/Identity.API/Startup.cs
src/Services/Ordering/Ordering.API/Ordering.API.csproj
src/Services/Ordering/Ordering.SignalrHub/Ordering.SignalrHub.csproj
src/Services/Ordering/Ordering.SignalrHub/Startup.cs
src/Services/Webhooks/Webhooks.API/Webhooks.API.csproj
src/Web/WebMVC/Startup.cs
src/Web/WebMVC/WebMVC.csproj
src/Web/WebSPA/Startup.cs
src/Web/WebSPA/WebSPA.csproj

Fixes : #1575 . It contains the following changes :
- Removes `dotnet.myget.org` package feed as it has been retired.
- Uses `Microsoft.AspNetCore.DataProtection.StackExchangeRedis` package instead of `Microsoft.AspNetCore.DataProtection.Redis`
- Downgrades `Microsoft.AspNetCore.Hosting.Abstractions` to `2.2.0`
- Removes unused following packages from the project 
- `Microsoft.AspNetCore.Razor.Design`
- `System.Reflection`

Removes dotnet.myget.org NuGetPackage feed references
