- README.md
Hi, I have fixed a typo in readme file.
> Fixed a typo from "mobilee" to "mobile"

- src/Console/eShopConsole/Properties/launchSettings.json
- src/Services/Basket/Basket.API/Properties/launchSettings.json
- src/Services/Catalog/Catalog.API/Properties/launchSettings.json
- src/Services/Ordering/Ordering.API/Properties/launchSettings.json
- src/Web/WebMVC/Properties/launchSettings.json
Reverts dotnet/eShopOnContainers#106
> Revert "Removes Docker profile from launchSettings.json"

- src/Console/eShopConsole/Properties/launchSettings.json
- src/Services/Basket/Basket.API/Properties/launchSettings.json
- src/Services/Catalog/Catalog.API/Properties/launchSettings.json
- src/Services/Ordering/Ordering.API/Properties/launchSettings.json
- src/Web/WebMVC/Properties/launchSettings.json
Reverts dotnet/eShopOnContainers#108
> Revert "Revert "Removes Docker profile from launchSettings.json""

- src/Mobile/AndroidSDKManager.ps1
- src/Mobile/README.md
- src/Mobile/eShopOnContainers/eShopOnContainers.Droid/eShopOnContainers.Droid.csproj
- src/Mobile/eShopOnContainers/eShopOnContainers.TestRunner.Droid/eShopOnContainers.TestRunner.Droid.csproj
- src/Mobile/eShopOnContainers/eShopOnContainers.TestRunner.iOS/eShopOnContainers.TestRunner.iOS.csproj
- src/Mobile/eShopOnContainers/eShopOnContainers.iOS/eShopOnContainers.iOS.csproj
Updated README
Added powershell script to get Android SDK
> Changed project error message language

- src/Mobile/eShopOnContainers/eShopOnContainers.Core/App.xaml.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Extensions/AnimationExtension.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Helpers/ServicesHelper.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Helpers/Settings.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/Navigation/INavigationService.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Services/Navigation/NavigationService.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Validations/ValidatableObject.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/Base/ExtendedBindableObject.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/Base/ViewModelBase.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/Base/ViewModelLocator.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/BasketViewModel.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/CatalogViewModel.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/CheckoutViewModel.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/LoginViewModel.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/MainViewModel.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/OrderDetailViewModel.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/ProfileViewModel.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/SettingsViewModel.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/BasketView.xaml
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/CatalogView.xaml
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/CatalogView.xaml.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/CheckoutView.xaml
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/LoginView.xaml
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/MainView.xaml
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/MainView.xaml.cs
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/OrderDetailView.xaml
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/ProfileView.xaml
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/SettingsView.xaml
- src/Mobile/eShopOnContainers/eShopOnContainers.Core/eShopOnContainers.Core.csproj
Reverts dotnet/eShopOnContainers#85
The changes are great but there seems to be a problem with Docker's local services connection. We need to check this out.
> Revert "ViewModelLocator now connects view models to views, rather than NavigationService."

- src/Services/Catalog/Catalog.API/Infrastructure/CatalogContextSeed.cs
- src/Services/Catalog/Catalog.API/Startup.cs
Removed the catch with retry logic from CatalogContextSeed and create a retry loop at startup for db availability #76 #75
> Removed the catch with retry logic from CatalogContextSeed 

- src/BuildingBlocks/EventBus/EventBus/Events/IntegrationEvent.cs
- src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs
- src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj
Replaced Tuple by C#7 multiple return statement
Replaced private set only used in ctor by readonly prop
Please @dsrodenas review and merge if feel ok!
> Using some C#7 features

- src/Services/Identity/Identity.API/Configuration/Config.cs
- src/Services/Identity/Identity.API/Controllers/AccountController.cs
- src/Services/Identity/Identity.API/Controllers/ConsentController.cs
- src/Services/Identity/Identity.API/Identity.API.csproj
- src/Services/Identity/Identity.API/Models/AccountViewModels/ConsentViewModel.cs
- src/Services/Identity/Identity.API/Startup.cs
- src/Web/WebMVC/Startup.cs
> Upgrade to Identity Server 4 rtm

- src/Services/Ordering/Ordering.API/Application/Queries/IOrderQueries.cs
- src/Services/Ordering/Ordering.API/Application/Queries/OrderQueries.cs
- test/Services/UnitTest/Ordering/Application/OrdersWebApiTest.cs
Reverts dotnet-architecture/eShopOnContainers#178
> Revert "Fix API signatures for collections"

- cli-mac/build-bits.sh
- docker-compose.ci.build.yml
While at it, update the sh script too.
I’ll remove the WIP label once I test this on the PC
> Fix mac ci build

- cli-mac/build-bits.sh
- docker-compose.ci.build.yml
Reverts dotnet-architecture/eShopOnContainers#190
> Revert "Fix mac ci build"

- cli-windows/add-firewall-rules-for-sts-auth-thru-docker.ps1
> ports in log msgs changed from 5105 to 5110

- src/Services/Location/Locations.API/Locations.API.csproj
- src/Services/Location/Locations.API/Program.cs
- src/Services/Payment/Payment.API/Payment.API.csproj
- src/Services/Payment/Payment.API/Program.cs
- src/Web/WebStatus/Program.cs
- src/Web/WebStatus/Views/Shared/_Layout.cshtml
- src/Web/WebStatus/WebStatus.csproj
deleted link to ApplicationInsights  in 3 projects.
> ApplicationInsights deleted from 3 projects.

- src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/Order.cs
- src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/OrderItem.cs
- test/Services/UnitTest/Ordering/Builders.cs
- test/Services/UnitTest/Ordering/Domain/OrderAggregateTest.cs
This PR fix this issue https://github.com/dotnet-architecture/eShopOnContainers/issues/263.
> Fix bug #263

- src/Services/Basket/Basket.API/Infrastructure/Filters/HttpGlobalExceptionFilter.cs
- src/Services/Basket/Basket.API/Infrastructure/Filters/JsonErrorResponse.cs
- src/Services/Basket/Basket.API/Infrastructure/Filters/ValidateModelStateFilter.cs
- src/Services/Basket/Basket.API/Model/BasketItem.cs
- src/Services/Basket/Basket.API/Startup.cs
- src/Web/WebSPA/Client/modules/basket/basket.component.html
- src/Web/WebSPA/Client/modules/basket/basket.component.ts
- src/Web/WebSPA/Client/modules/orders/orders.component.ts
- src/Web/WebSPA/Client/modules/shared/services/data.service.ts
Hi,
This PR fix the issue https://github.com/dotnet-architecture/eShopOnContainers/issues/259.
I've implemented validation at Basket.API level using an ActionFilterAttribute to validate the model state and implemented IValidatableObject in BasketItem DTO.
> Fix issue #259

- src/Web/WebSPA/Client/modules/shared/services/basket.wrapper.service.ts
Hi, 
This PR fix the issue https://github.com/dotnet-architecture/eShopOnContainers/issues/283
> Fix bug #283

- src/Web/WebSPA/Client/modules/basket/basket.component.html
- src/Web/WebSPA/Client/modules/basket/basket.component.ts
This PR fix this issue https://github.com/dotnet-architecture/eShopOnContainers/issues/259
> Fix bug #259

- src/Services/Basket/Basket.API/Dockerfile.nanowin
- src/Services/Catalog/Catalog.API/Dockerfile.nanowin
- src/Services/Location/Locations.API/Dockerfile.nanowin
- src/Services/Marketing/Marketing.API/Dockerfile.nanowin
- src/Services/Ordering/Ordering.API/Dockerfile.nanowin
- src/Services/Payment/Payment.API/Dockerfile.nanowin
- src/Web/WebMVC/Dockerfile.nanowin
- src/Web/WebSPA/Dockerfile.nanowin
- src/Web/WebStatus/Dockerfile.nanowin
windows docker files update to 2.0 base images
> windows docker files update to 2.0 base images

- k8s/sql-data.yaml
Using new Docker Sql Server for Linux Image, Release Candidate 2
> Updated Docker image version to Sql Server RC2

- docker-compose.nobuild.yml
looks like this file has missed latest refactoring
> NoBuild missed some images

- k8s/basket-data.yaml
- k8s/keystore-data.yaml
- k8s/rabbitmq.yaml
sync k8 images with local windows/linux images for consistency
> sync k8 images with local windows/linux images for consistency

- docker-compose.override.yml
- k8s/deploy.ps1
> Grace period rudement fix

- README.md
Fixed a simple spelling mistake.
> Fixed miroservices spelling mistake

- k8s/gen-k8s-env.ps1
Non-preview parameters specified
@CESARDELATORRE https://github.com/dotnet-architecture/eShopOnContainers/issues/331
> Explicitly specifying parameters for az acs create

- docker-compose.override.yml
https://github.com/dotnet-architecture/eShopOnContainers/issues/375
@CESARDELATORRE @ramonTC @eiximenis
> Payment API orchestrator missed from compose-overrride

- src/Services/Identity/Identity.API/Identity.API.csproj
- src/Services/Identity/Identity.API/Migrations/ConfigurationDb/20170927170433_Config.Designer.cs
- src/Services/Identity/Identity.API/Migrations/ConfigurationDb/20170927170433_Config.cs
- src/Services/Identity/Identity.API/Migrations/ConfigurationDb/ConfigurationDbContextModelSnapshot.cs
- src/Services/Identity/Identity.API/Migrations/PersistedGrantDb/20170927170423_Grants.Designer.cs
- src/Services/Identity/Identity.API/Migrations/PersistedGrantDb/20170927170423_Grants.cs
- src/Services/Identity/Identity.API/Startup.cs
currently we are using rc1 and it's not RTM. 
migrations updated and startup.cs for identity project
@CESARDELATORRE @ramonTC @eiximenis
> identityserver4 to 2.0 rtm

- src/BuildingBlocks/DataProtection/DataProtection/DataProtection.csproj
- src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks.SqlServer/Microsoft.Extensions.HealthChecks.SqlServer.csproj
- src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks/Microsoft.Extensions.HealthChecks.csproj
all projects finally migrated to .net standard 2.0
@CESARDELATORRE @ramonTC @eiximenis
> last .net core 2.0 part

- src/BuildingBlocks/DataProtection/DataProtection/DataProtection.csproj
- src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks.SqlServer/Microsoft.Extensions.HealthChecks.SqlServer.csproj
- src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks/Microsoft.Extensions.HealthChecks.csproj
Reverts dotnet-architecture/eShopOnContainers#381
> Revert "last .net core 2.0 part"

- src/Web/WebStatus/Views/Shared/_Layout.cshtml
https://github.com/dotnet-architecture/eShopOnContainers/issues/377
> WebStatus returns 404 for js/site.js that don't exists 

- src/Services/Ordering/Ordering.API/Application/Queries/IOrderQueries.cs
- src/Services/Ordering/Ordering.API/Application/Queries/OrderQueries.cs
- src/Services/Ordering/Ordering.API/Application/Queries/OrderViewModel.cs
- src/Services/Ordering/Ordering.API/Controllers/OrdersController.cs
https://github.com/dotnet-architecture/eShopOnContainers/issues/366
Without it- we can't specify response types for swagger.
also dynamic types in this case- have no benefits
@CESARDELATORRE @ramonTC @eiximenis
> no more dynamics as a return types from controllers in Ordering app

- src/Mobile/README.md
Corrected certain typo errors in the file, changed some grammatical structure where applicable for better reading experience and added some elaborations for some acronyms.
> Fixed certain typos in README.md file

- src/Web/WebMVC/Views/Order/Index.cshtml
- src/Web/WebMVC/Views/Shared/_Layout.cshtml
In Rider these two items cause an error in the solution view - however I can still build OK.
> Code clean up to remove solution errors in the Rider IDE

- deploy/az/createresources.sh
- deploy/az/readme.md
update Createresources.sh readme
> Update createresources Readme.

- k8s/README.CICD.k8s.md
- k8s/README.k8s.md
- k8s/gen-k8s-env-aks.ps1
https://github.com/dotnet-architecture/eShopOnContainers/issues/414
@CESARDELATORRE
> AKS instead of ACS

- src/Services/Basket/Basket.API/Basket.API.csproj
- src/Services/Catalog/Catalog.API/Catalog.API.csproj
- src/Services/Identity/Identity.API/Identity.API.csproj
- src/Services/Location/Locations.API/Locations.API.csproj
- src/Services/Marketing/Marketing.API/Marketing.API.csproj
- src/Services/Ordering/Ordering.API/Ordering.API.csproj
- src/Services/Payment/Payment.API/Payment.API.csproj
- src/Web/WebMVC/WebMVC.csproj
- src/Web/WebSPA/WebSPA.csproj
- src/Web/WebStatus/WebStatus.csproj
> Microsoft.ApplicationInsights.ServiceFabric to 2.0.1-beta1

- src/Services/Ordering/Ordering.API/Application/Behaviors/LoggingBehavior.cs
- src/Services/Ordering/Ordering.API/Application/Behaviors/ValidatorBehavior.cs
- src/Services/Ordering/Ordering.API/Application/Commands/CancelOrderCommandHandler.cs
- src/Services/Ordering/Ordering.API/Application/Commands/CreateOrderCommandHandler.cs
- src/Services/Ordering/Ordering.API/Application/Commands/IdentifiedCommandHandler.cs
- src/Services/Ordering/Ordering.API/Application/Commands/ShipOrderCommandHandler.cs
- src/Services/Ordering/Ordering.API/Application/DomainEventHandlers/BuyerAndPaymentMethodVerified/UpdateOrderWhenBuyerAndPaymentMethodVerifiedDomainEventHandler.cs
- src/Services/Ordering/Ordering.API/Application/DomainEventHandlers/OrderGracePeriodConfirmed/OrderStatusChangedToAwaitingValidationDomainEventHandler.cs
- src/Services/Ordering/Ordering.API/Application/DomainEventHandlers/OrderPaid/OrderStatusChangedToPaidDomainEventHandler.cs
- src/Services/Ordering/Ordering.API/Application/DomainEventHandlers/OrderStartedEvent/ValidateOrAddBuyerAggregateWhenOrderStartedDomainEventHandler.cs
- src/Services/Ordering/Ordering.API/Application/DomainEventHandlers/OrderStockConfirmed/OrderStatusChangedToStockConfirmedDomainEventHandler.cs
- src/Services/Ordering/Ordering.API/Infrastructure/AutofacModules/MediatorModule.cs
- src/Services/Ordering/Ordering.API/Ordering.API.csproj
- src/Services/Ordering/Ordering.Domain/Ordering.Domain.csproj
> MediatR from 3 to 4

- src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj
- src/BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLogEF.csproj
- src/BuildingBlocks/HealthChecks/src/Microsoft.AspNetCore.HealthChecks/Microsoft.AspNetCore.HealthChecks.csproj
- src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks.AzureStorage/Microsoft.Extensions.HealthChecks.AzureStorage.csproj
- src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks.SqlServer/Microsoft.Extensions.HealthChecks.SqlServer.csproj
- src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks/Microsoft.Extensions.HealthChecks.csproj
- src/BuildingBlocks/Resilience/Resilience.Http/Resilience.Http.csproj
- src/BuildingBlocks/WebHostCustomization/WebHost.Customization/WebHost.Customization.csproj
- src/Services/Basket/Basket.API/Basket.API.csproj
- src/Services/Basket/Basket.API/Dockerfile
- src/Services/Catalog/Catalog.API/Catalog.API.csproj
- src/Services/Catalog/Catalog.API/Dockerfile
- src/Services/Identity/Identity.API/Dockerfile
- src/Services/Identity/Identity.API/Identity.API.csproj
- src/Services/Location/Locations.API/Dockerfile
- src/Services/Location/Locations.API/Locations.API.csproj
- src/Services/Marketing/Marketing.API/Dockerfile
- src/Services/Marketing/Marketing.API/Marketing.API.csproj
- src/Services/Ordering/Ordering.API/Dockerfile
- src/Services/Ordering/Ordering.API/Ordering.API.csproj
- src/Services/Ordering/Ordering.Infrastructure/Ordering.Infrastructure.csproj
- src/Services/Payment/Payment.API/Dockerfile
- src/Services/Payment/Payment.API/Payment.API.csproj
- src/Web/WebMVC/Dockerfile
- src/Web/WebMVC/WebMVC.csproj
- src/Web/WebSPA/Dockerfile
- src/Web/WebSPA/WebSPA.csproj
- src/Web/WebStatus/Dockerfile
- src/Web/WebStatus/WebStatus.csproj
> microsoft packages to latest. including Logging from .net standard 1.3 to 2.0 upgrade

- src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks.SqlServer/Microsoft.Extensions.HealthChecks.SqlServer.csproj
- src/Services/Location/Locations.API/Locations.API.csproj
- src/Services/Marketing/Marketing.API/Dto/UserLocationDTO.cs
- src/Services/Marketing/Marketing.API/Infrastructure/Filters/AuthorizeCheckOperationFilter.cs
- src/Services/Marketing/Marketing.API/Infrastructure/MarketingMigrations/20170615163431_Init.cs
- src/Services/Marketing/Marketing.API/Infrastructure/MarketingMigrations/20170629102516_added-campaign-details.cs
- src/Services/Marketing/Marketing.API/Infrastructure/MarketingMigrations/MarketingContextModelSnapshot.cs
- src/Services/Marketing/Marketing.API/Infrastructure/Middlewares/ByPassAuthMiddleware.cs
- src/Services/Marketing/Marketing.API/Infrastructure/Repositories/MarketingDataRepository.cs
- src/Services/Marketing/Marketing.API/Marketing.API.csproj
- src/Services/Marketing/Marketing.API/Model/Location.cs
- src/Services/Marketing/Marketing.API/Model/MarketingData.cs
- src/Services/Ordering/Ordering.API/Ordering.API.csproj
small fixes
@CESARDELATORRE  @ramonTC  
could be a first step to implement https://github.com/dotnet-architecture/eShopOnContainers/issues/439
> mongo 2.5 (prep for retryable writes) and some small fixes

- src/BuildingBlocks/HealthChecks/src/Microsoft.Extensions.HealthChecks.AzureStorage/Microsoft.Extensions.HealthChecks.AzureStorage.csproj
- src/Services/Basket/Basket.API/Basket.API.csproj
- src/Services/Catalog/Catalog.API/Catalog.API.csproj
- src/Services/Identity/Identity.API/Identity.API.csproj
- src/Services/Location/Locations.API/Locations.API.csproj
- src/Services/Marketing/Marketing.API/Marketing.API.csproj
- src/Services/Ordering/Ordering.API/Ordering.API.csproj
- src/Services/Payment/Payment.API/Payment.API.csproj
- src/Web/WebMVC/WebMVC.csproj
- src/Web/WebSPA/WebSPA.csproj
- src/Web/WebStatus/WebStatus.csproj
"Microsoft.ApplicationInsights.Kubernetes" Version="1.0.0-beta2"
notified from https://github.com/Microsoft/ApplicationInsights-Kubernetes/issues/74#issuecomment-350786279
> "Microsoft.ApplicationInsights.Kubernetes" Version="1.0.0-beta2"

- k8s/frontend.yaml
> nginx image update to latest

- k8s/deploy.sh
- k8s/eshop-namespace.yaml
The script has some limitations compared to the PowerShell version--see comments in the script. @CESARDELATORRE thought it is a useful starting point regardless.
> Add deployment script for Mac/Linux

- src/Services/Catalog/Catalog.API/Infrastructure/CatalogContextSeed.cs
- src/Services/Identity/Identity.API/Data/ApplicationDbContextSeed.cs
- src/Services/Identity/Identity.API/Data/ConfigurationDbContextSeed.cs
- src/Services/Marketing/Marketing.API/Infrastructure/MarketingContextSeed.cs
- src/Services/Ordering/Ordering.API/Infrastructure/OrderingContextSeed.cs
in all the Context Seeding methods we call AddRange instead of AddRangeAsync even though the methods themselves are marked async.
> Changed AddRange to AddRangeAsync

- deploy/az/servicebus/readme.md
- k8s/conf_cloud.yml
I spend about an hour recognizing that I need key from topics, not from namespace
This fix maybe will save sometime to others.
> make servicebus deployment more accurate and self describable

- test/Services/IntegrationTests/Services/Basket/BasketScenarios.cs
Fixed dummy basket data so the CreateOrderCommand (created from basket data) passes validations.
> Fix aborting integration tests

- k8s/gen-k8s-env-aks.ps1
> aks cluster version in a script

- cli-windows/build-images.ps1
- cli-windows/start-windows-containers.ps1
- docker-compose.override.yml
- docker-compose.windows.yml
- docker-compose.yml
- run-docker-compose-build.ps1
This fixes existing windows script to handle fixes in #630.
Also rearranged the services order in docker-compose*.yml to be the same as that in docker-compose.yml.
> Fix windows scripts

- src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs
> Fix spelling

- src/BuildingBlocks/EventBus/IntegrationEventLogEF/Services/IntegrationEventLogService.cs
Convert some magic strings to use "nameof" operator
> Convert some magic strings to use "nameof" operator

- k8s/helm/apigwmm/values.yaml
- k8s/helm/apigwms/values.yaml
- k8s/helm/apigwwm/values.yaml
- k8s/helm/apigwws/values.yaml
> Fixes 401 after login in helm deployments

- src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/OrderStatus.cs
This PR fixes duplication of "using Seedwork;".
> fix: duplicated "using Seedwork;"

- src/Services/Basket/Basket.API/BasketSettings.cs
It seems that there is unused property EventBusConnection present in BasketSettings class.
I have removed it, please review.
> Removed unused EventBusConnection property

- src/BuildingBlocks/EventBus/EventBus/Events/IntegrationEvent.cs
…ame event type #645 
https://github.com/dotnet-architecture/eShopOnContainers/issues/645
> [Bug] Deserialization of IntegrationEvent #667

- src/Services/Basket/Basket.FunctionalTests/BasketScenarios.cs
- src/Services/Ordering/Ordering.FunctionalTests/OrderingScenarios.cs
- src/Web/WebMVC/Controllers/CampaignsController.cs
- src/Web/WebMVC/Controllers/OrderManagementController.cs
- src/Web/WebMVC/Services/BasketService.cs
- src/Web/WebMVC/Services/IBasketService.cs
- src/Web/WebMVC/Services/ILocationService.cs
- src/Web/WebMVC/Services/IOrderingService.cs
- src/Web/WebMVC/Services/LocationService.cs
- src/Web/WebMVC/Services/ModelDTOs/BasketDTO.cs
- src/Web/WebMVC/Services/ModelDTOs/LocationDTO.cs
- src/Web/WebMVC/Services/ModelDTOs/OrderDTO.cs
- src/Web/WebMVC/Services/ModelDTOs/OrderProcessAction.cs
- src/Web/WebMVC/Services/OrderingService.cs
- src/Web/WebMVC/ViewModels/Order.cs
- test/ServicesTests/Application.FunctionalTests/Services/Ordering/OrderingScenarios.cs
These are not really (entity) Models but just DTOs for the services.
Closes https://github.com/dotnet-architecture/eShopOnContainers/issues/564
> Refactor ModelDTOs in WebMVC for a more consistent folder structure

- src/BuildingBlocks/EventBus/EventBus/Extensions/GenericTypeExtensions.cs
- src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs
- src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs
- src/Services/Basket/Basket.FunctionalTests/BasketScenarios.cs
- src/Services/Ordering/Ordering.API/Application/Behaviors/LoggingBehavior.cs
- src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs
- src/Services/Ordering/Ordering.API/Application/Behaviors/ValidatorBehavior.cs
- src/Services/Ordering/Ordering.API/Application/Commands/IdentifiedCommandHandler.cs
- src/Services/Ordering/Ordering.API/Application/IntegrationEvents/EventHandling/GracePeriodConfirmedIntegrationEventHandler.cs
- src/Services/Ordering/Ordering.API/Application/IntegrationEvents/EventHandling/OrderPaymentFailedIntegrationEventHandler.cs
- src/Services/Ordering/Ordering.API/Application/IntegrationEvents/EventHandling/OrderPaymentSuccededIntegrationEventHandler.cs
- src/Services/Ordering/Ordering.API/Application/IntegrationEvents/EventHandling/OrderStockConfirmedIntegrationEventHandler.cs
- src/Services/Ordering/Ordering.API/Application/IntegrationEvents/EventHandling/OrderStockRejectedIntegrationEventHandler.cs
- src/Services/Ordering/Ordering.API/Application/IntegrationEvents/EventHandling/UserCheckoutAcceptedIntegrationEventHandler.cs
- src/Services/Ordering/Ordering.API/Controllers/OrdersController.cs
- src/Services/Ordering/Ordering.FunctionalTests/OrderingScenarios.cs
Add logging of subscription events for diagnosing issues.
> Add logging of subscription events

- src/Web/WebMVC/Infrastructure/HttpClientRequestIdDelegatingHandler.cs
Fixes https://github.com/dotnet-architecture/eShopOnContainers/issues/708
Thanks to @stanoislav
> Fix duplicate x-requestid headers

- src/Web/WebStatus/appsettings.json
> Fix JSON structure error.

- src/Web/WebStatus/appsettings.json
Repair bad fix in PR https://github.com/dotnet-architecture/eShopOnContainers/pull/957
> Fix bad previous fix

- src/Services/Catalog/Catalog.API/Infrastructure/Filters/HttpGlobalExceptionFilter.cs
> Fixed typo in HttpGlobalExceptionFilter

- src/Services/Ordering/Ordering.SignalrHub/NotificationHub.cs
Correcting a typo from a previous commit.
> Fix method name in OnDisconnectAsync

- README.md
This PR is used to add a note about third-party EventBus implementation in README.
> Update README add note for EventBus

- k8s/helm/deploy-all.sh
Adds a bash version of the `deploy-all.ps1` Helm deployment script for use on MacOS and Linux machines.
> Added bash version of the Helm deploy script

- src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs
Because when channel create the Subscribe is not register, so the previously stored message may lose. This fix split the channel create and consumer create, when Subscribe registered then call the consumer create function.
> Split RabbitMQ channel create and consumer create.

- src/Services/Ordering/Ordering.Domain/AggregatesModel/BuyerAggregate/CardType.cs
- src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/OrderStatus.cs
- src/Services/Ordering/Ordering.Domain/SeedWork/Enumeration.cs
Partially applying changes proposed in PR #704.
Closes #704
> Simplify Enumeration and CardType classes as proposed in PR #704

- src/BuildingBlocks/EventBus/EventBus/InMemoryEventBusSubscriptionsManager.cs
Prevent a possible race condition in InMemoryEventBusSubscriptionsManager
> Concurrency fix for EventBus

- src/Services/Basket/Basket.FunctionalTests/Basket.FunctionalTests.csproj
- src/Services/Catalog/Catalog.FunctionalTests/Catalog.FunctionalTests.csproj
- src/Services/Location/Locations.FunctionalTests/Locations.FunctionalTests.csproj
fix missing references that were causing functional tests to fail.
> fix references in functional test projects

- src/Services/Identity/Identity.API/Views/Shared/_LoginPartial.cshtml
Logout form will now point to the correct action.
> change form action from non-existent Logoff to Logout

- src/ApiGateways/Mobile.Bff.Shopping/aggregator/Filters/AuthorizeCheckOperationFilter.cs
- src/ApiGateways/Web.Bff.Shopping/aggregator/Filters/AuthorizeCheckOperationFilter.cs
- src/Services/Basket/Basket.API/Infrastructure/Filters/AuthorizeCheckOperationFilter.cs
- src/Services/Location/Locations.API/Infrastructure/Filters/AuthorizeCheckOperationFilter.cs
- src/Services/Marketing/Marketing.API/Infrastructure/Filters/AuthorizeCheckOperationFilter.cs
- src/Services/Ordering/Ordering.API/Infrastructure/Filters/AuthorizeCheckOperationFilter.cs
- src/Services/Webhooks/Webhooks.API/Infrastructure/AuthorizeCheckOperationFilter.cs
Fixes https://github.com/dotnet-architecture/eShopOnContainers/issues/744
> Remove deprecated Swashbuckle API, refactor

- docker-compose.override.yml
- src/Services/Ordering/Ordering.API/Application/Validations/CancelOrderCommandValidator.cs
- src/Services/Ordering/Ordering.API/Application/Validations/CreateOrderCommandValidator.cs
- src/Services/Ordering/Ordering.API/Application/Validations/IdentifiedCommandValidator.cs
- src/Services/Ordering/Ordering.API/Application/Validations/ShipOrderCommandValidator.cs
Add creation event traces to Validator classes to validate issue #1041
> Add log traces

- k8s/helm/app.yaml
- k8s/helm/basket-api/templates/configmap.yaml
- k8s/helm/catalog-api/templates/configmap.yaml
- k8s/helm/identity-api/templates/configmap.yaml
- k8s/helm/inf.yaml
- k8s/helm/locations-api/templates/configmap.yaml
- k8s/helm/marketing-api/templates/configmap.yaml
- k8s/helm/mobileshoppingagg/templates/configmap.yaml
- k8s/helm/ordering-api/templates/configmap.yaml
- k8s/helm/ordering-backgroundtasks/templates/configmap.yaml
- k8s/helm/ordering-signalrhub/templates/configmap.yaml
- k8s/helm/payment-api/templates/configmap.yaml
- k8s/helm/webhooks-api/templates/configmap.yaml
- k8s/helm/webmvc/templates/configmap.yaml
- k8s/helm/webshoppingagg/templates/configmap.yaml
- k8s/helm/webspa/templates/configmap.yaml
- k8s/helm/webstatus/templates/configmap.yaml
Create an empty entry when AI instrumentation key is not provided in k8s/helm/inf.yaml
Fixes #1046
> Handle empty Application Insights instrumentation key

- src/Services/Ordering/Ordering.API/Application/IntegrationEvents/EventHandling/OrderPaymentSucceededIntegrationEventHandler.cs
- src/Services/Ordering/Ordering.API/Application/IntegrationEvents/Events/OrderPaymentSucceededIntegrationEvent.cs
- src/Services/Ordering/Ordering.API/Startup.cs
- src/Services/Payment/Payment.API/IntegrationEvents/EventHandling/OrderStatusChangedToStockConfirmedIntegrationEventHandler.cs
- src/Services/Payment/Payment.API/IntegrationEvents/Events/OrderPaymentSucceededIntegrationEvent.cs
Fixes https://github.com/dotnet-architecture/eShopOnContainers/issues/1119
> Fix OrderPaymentSuccededIntergrationEvent naming rule

- src/Web/WebSPA/README.md
Fix Image URLs on Read me file. It seems to be broken
> Fix Image URLs on Read me file

- src/Services/Identity/Identity.API/Startup.cs
- Closes https://github.com/dotnet-architecture/eShopOnContainers/issues/1278
- Closes https://github.com/dotnet-architecture/eShopOnContainers/issues/1280
> Error fixed, applied the cookie policy to lax mode

- src/Web/WebMVC/Services/ModelDTOs/LocationDTO.cs
- src/Web/WebMVC/Services/ModelDTOs/OrderDTO.cs
- src/Web/WebMVC/Services/ModelDTOs/OrderProcessAction.cs
Removed unused usings from ModelDTOs
> Removed unused usings from ModelDTOs

- src/Web/WebSPA/package-lock.json
Updated "minimist" version to 1.2.5
> Updated "minimist" version to 1.2.5

- deploy/windows/add-firewall-rules-for-sts-auth-thru-docker.ps1
the check shall be like ~ Get-NetFirewallRule -DisplayName eShopOnContainers-* -ErrorAction Stop
> Fixed firewall rules check and improved the script

- build/azure-devops/multiarch.yaml
https://github.com/dotnet-architecture/eShopOnContainers/issues/1412
> fix parameter error in multiarch job

- src/Web/WebSPA/package-lock.json
Updated sha hashes in packages-lock.json
> Fixes #1474: webspa container does not build when running docker-compose up

- deploy/azure/az/createresources.sh
> Fixed parameter bug create resource script

- src/Web/WebSPA/Client/modules/catalog/catalog.component.html
> Fixed invalid number format in webspa

- src/Web/WebSPA/package-lock.json
Updated webpack-subresource-integrity library as per `Dependabot` recommendation.
> Updated package version of webpack-subresource-integrity

- src/eShopOnContainers-ServicesAndWebApps.sln
Fixes #1504 - Added `Envoy` related configuration file in the solution file.
> Updated solution file.

- src/Services/Catalog/Catalog.API/Infrastructure/CatalogContextSeed.cs
- src/Services/Catalog/Catalog.API/Infrastructure/CatalogMigrations/CatalogContextModelSnapshot.cs
- src/Services/Catalog/Catalog.API/Setup/CatalogItems.csv
Update CatalogContextModelSnapshot.cs
> Fixed #1518 bug

- src/Web/WebSPA/package-lock.json
Updates `highlight.js` package `version:` to `10.4.0`
> Updated highlight.js version to latest.

- src/Services/Catalog/Catalog.API/IntegrationEvents/Events/ProductPriceChangedIntegrationEvent.cs
Was walking through the code while reading the ebook, saw 2 small errors in comments in a file. Thought I make a quick PR.
> Finished sentence and fixed spelling mistake.

- src/Services/Identity/Identity.API/Data/ApplicationDbContextSeed.cs
- src/Services/Identity/Identity.API/Setup/Users.csv
- src/Web/WebMVC/Infrastructure/Middlewares/ByPassAuthMiddleware.cs
Updated default expiration date of the credit card for demo user.
> Updated credit card default expiration value.

- README.md
Updates `Getting Started` section in the readme file.
> Updated getting started section in readme file.

- src/Web/WebSPA/package-lock.json
- src/Web/WebSPA/package.json
- Updates `typedoc` package to version `0.19.2`
- Updates `highlight.js` package to version `10.4.1`
> Updated packages to latest version.

- src/Services/Identity/Identity.API/Dockerfile
- src/Services/Identity/Identity.API/Identity.API.csproj
- src/Services/Identity/Identity.API/Models/AccountViewModels/ConsentInputModel.cs
- src/Services/Identity/Identity.API/Models/AccountViewModels/ConsentViewModel.cs
- src/Services/Identity/Identity.API/Models/AccountViewModels/ForgotPasswordViewModel.cs
- src/Services/Identity/Identity.API/Models/AccountViewModels/LoggedOutViewModel.cs
- src/Services/Identity/Identity.API/Models/AccountViewModels/LoginViewModel.cs
- src/Services/Identity/Identity.API/Models/AccountViewModels/LogoutViewModel.cs
- src/Services/Identity/Identity.API/Models/AccountViewModels/RegisterViewModel.cs
- src/Services/Identity/Identity.API/Models/AccountViewModels/ResetPasswordViewModel.cs
- src/Services/Identity/Identity.API/Models/AccountViewModels/SendCodeViewModel.cs
- src/Services/Identity/Identity.API/Models/AccountViewModels/VerifyCodeViewModel.cs
- src/Services/Identity/Identity.API/Models/ErrorViewModel.cs
- src/Services/Identity/Identity.API/Models/ManageViewModels/AddPhoneNumberViewModel.cs
- src/Services/Identity/Identity.API/Models/ManageViewModels/ChangePasswordViewModel.cs
- src/Services/Identity/Identity.API/Models/ManageViewModels/ConfigureTwoFactorViewModel.cs
- src/Services/Identity/Identity.API/Models/ManageViewModels/FactorViewModel.cs
- src/Services/Identity/Identity.API/Models/ManageViewModels/IndexViewModel.cs
- src/Services/Identity/Identity.API/Models/ManageViewModels/SetPasswordViewModel.cs
- src/Services/Identity/Identity.API/Models/ManageViewModels/VerifyPhoneNumberViewModel.cs
- src/Services/Identity/Identity.API/Program.cs
- Migrate to .NET 5
- Apply C# 9 features
- Update nugets
- Update Dockerfiles
> identity api net 5 migration

- src/ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
- src/ApiGateways/Mobile.Bff.Shopping/aggregator/Infrastructure/GrpcExceptionInterceptor.cs
- src/ApiGateways/Mobile.Bff.Shopping/aggregator/Mobile.Shopping.HttpAggregator.csproj
- src/ApiGateways/Mobile.Bff.Shopping/aggregator/Services/CatalogService.cs
- src/ApiGateways/Mobile.Bff.Shopping/aggregator/Startup.cs
- src/ApiGateways/Web.Bff.Shopping/aggregator/Infrastructure/GrpcExceptionInterceptor.cs
- src/ApiGateways/Web.Bff.Shopping/aggregator/Services/CatalogService.cs
- src/ApiGateways/Web.Bff.Shopping/aggregator/Startup.cs
- src/Services/Catalog/Catalog.API/Catalog.API.csproj
- src/Services/Catalog/Catalog.API/CatalogSettings.cs
- src/Services/Catalog/Catalog.API/Dockerfile
- src/Services/Catalog/Catalog.API/Program.cs
- src/Services/Catalog/Catalog.FunctionalTests/Catalog.FunctionalTests.csproj
- src/Services/Catalog/Catalog.UnitTests/Catalog.UnitTests.csproj
- Migrate to .NET 5
- Ensure tests work OK (Unit + Functional)
- Apply C# 9 features
- Update nugets
- Update Dockerfiles
- Apply gRPC performance improvement suggestion
> catalog api net 5 migration

- src/Services/Ordering/Ordering.FunctionalTests/appsettings.json
Added IdentityUrlExternal to src\Services\Ordering\Ordering.FunctionalTests\appsettings.json; sorted the properties
> Fixed Issue #1410

- src/Mobile/eShopOnContainers/eShopOnContainers.Core/Views/MainView.xaml
Incorrect ContentPage.ToolbarItems in a TabbedPage
> Incorrect ContentPage.ToolbarItems in a TabbedPage
